import mongoose from 'mongoose'
import detenv from 'dotenv'
import colors from 'colors'
import users from './data/users.js'
import products from './data/products.js'
import User from './models/userModel.js'
import Product from './models/ProductModel.js'
import Order from './models/ordersModel.js'